// <auto-generated />
using EntityFrameworkCoreDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCoreDemo.Migrations
{
    [DbContext(typeof(SportsDbContext))]
    [Migration("20230530093729_SportsMigration")]
    partial class SportsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCoreDemo.Models.Cricketers", b =>
                {
                    b.Property<int>("cricketerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cricketerId"));

                    b.Property<string>("cricketerLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cricketerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cricketerId");

                    b.ToTable("Cricketers");
                });

            modelBuilder.Entity("EntityFrameworkCoreDemo.Models.Footballers", b =>
                {
                    b.Property<int>("footballerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("footballerId"));

                    b.Property<string>("footballerLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("footballerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("footballerId");

                    b.ToTable("Footballers");
                });
#pragma warning restore 612, 618
        }
    }
}
